# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './/jackfish/gui/review_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReviewUI(object):
    def setupUi(self, ReviewUI):
        ReviewUI.setObjectName("ReviewUI")
        ReviewUI.resize(886, 571)
        self.plot_one = PlotWidget(ReviewUI)
        self.plot_one.setGeometry(QtCore.QRect(20, 20, 641, 461))
        self.plot_one.setObjectName("plot_one")
        self.load_data_push = QtWidgets.QPushButton(ReviewUI)
        self.load_data_push.setGeometry(QtCore.QRect(20, 500, 181, 41))
        self.load_data_push.setObjectName("load_data_push")
        self.dropdown_one = QtWidgets.QComboBox(ReviewUI)
        self.dropdown_one.setGeometry(QtCore.QRect(680, 20, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.dropdown_one.setPalette(palette)
        self.dropdown_one.setObjectName("dropdown_one")
        self.dropdown_two = QtWidgets.QComboBox(ReviewUI)
        self.dropdown_two.setGeometry(QtCore.QRect(680, 60, 180, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.dropdown_two.setPalette(palette)
        self.dropdown_two.setObjectName("dropdown_two")
        self.dropdown_three = QtWidgets.QComboBox(ReviewUI)
        self.dropdown_three.setGeometry(QtCore.QRect(680, 100, 180, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.dropdown_three.setPalette(palette)
        self.dropdown_three.setObjectName("dropdown_three")
        self.start_sec_edit = QtWidgets.QLineEdit(ReviewUI)
        self.start_sec_edit.setGeometry(QtCore.QRect(220, 520, 81, 25))
        self.start_sec_edit.setObjectName("start_sec_edit")
        self.end_sec_edit = QtWidgets.QLineEdit(ReviewUI)
        self.end_sec_edit.setGeometry(QtCore.QRect(320, 520, 81, 25))
        self.end_sec_edit.setObjectName("end_sec_edit")
        self.label = QtWidgets.QLabel(ReviewUI)
        self.label.setGeometry(QtCore.QRect(220, 500, 81, 17))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ReviewUI)
        self.label_2.setGeometry(QtCore.QRect(320, 500, 81, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.norm_check = QtWidgets.QCheckBox(ReviewUI)
        self.norm_check.setGeometry(QtCore.QRect(680, 140, 161, 23))
        self.norm_check.setObjectName("norm_check")

        self.retranslateUi(ReviewUI)
        QtCore.QMetaObject.connectSlotsByName(ReviewUI)

    def retranslateUi(self, ReviewUI):
        _translate = QtCore.QCoreApplication.translate
        ReviewUI.setWindowTitle(_translate("ReviewUI", "Dialog"))
        self.load_data_push.setText(_translate("ReviewUI", "Load Data"))
        self.start_sec_edit.setText(_translate("ReviewUI", "0"))
        self.end_sec_edit.setText(_translate("ReviewUI", "10"))
        self.label.setText(_translate("ReviewUI", "Start"))
        self.label_2.setText(_translate("ReviewUI", "End"))
        self.norm_check.setText(_translate("ReviewUI", "Normalize (0 to 1)"))
from pyqtgraph import PlotWidget
